Repository kureung/good-price-good-product, pull requests merged in 2022-06, with the labels that each got.

#73 refactor : 연관관계 코드 수정
  src/main/java/kr/co/gpgp/domain/address/entity/Address.java
  src/main/java/kr/co/gpgp/domain/address/service/AddressService.java
  src/main/java/kr/co/gpgp/domain/delivery/entity/Delivery.java
  src/main/java/kr/co/gpgp/domain/delivery/repository/DeliveryRepository.java
  src/main/java/kr/co/gpgp/domain/delivery/service/DeliveryService.java
  src/main/java/kr/co/gpgp/domain/requirement/entity/Requirement.java
  src/main/java/kr/co/gpgp/domain/user/entity/User.java
  src/main/java/kr/co/gpgp/domain/user/service/UserService.java
Labels: 🛠 리팩토링

#89 faet: 배송 DTO 추가(#68)
  src/main/java/kr/co/gpgp/domain/delivery/dto/DeliveryRequest.java
  src/main/java/kr/co/gpgp/domain/delivery/dto/DeliveryResponse.java
Labels: 🚚 배송

#84 feat: address (service,entity,TDD) 변경 및 추가
  src/main/java/kr/co/gpgp/domain/address/dto/AddressRequest.java
  src/main/java/kr/co/gpgp/domain/address/dto/AddressResponse.java
  src/main/java/kr/co/gpgp/domain/address/entity/Address.java
  src/main/java/kr/co/gpgp/domain/address/repository/AddressRepository.java
  src/main/java/kr/co/gpgp/domain/address/repository/AddressRepositoryCustom.java
  src/main/java/kr/co/gpgp/domain/address/repository/AddressRepositoryCustomImpl.java
  src/main/java/kr/co/gpgp/domain/address/service/AddressService.java
  src/test/java/kr/co/gpgp/domain/address/service/AddressServiceTest.java
Labels: 🛠 리팩토링, 🏠 주소지

#90 refactor: 배송 enum 리펙토링
  src/main/java/kr/co/gpgp/domain/delivery/entity/Delivery.java
  src/main/java/kr/co/gpgp/domain/delivery/entity/enums/DeliveryStatusImpl.java
  src/test/java/kr/co/gpgp/domain/delivery/entity/DeliveryTest.java
Labels: 🛠 리팩토링

#100 feat: OAuth2 로그인 2
  build.gradle
  src/main/java/kr/co/gpgp/auth/config/CustomOAuth2Provider.java
  src/main/java/kr/co/gpgp/auth/config/SecurityConfig.java
  src/main/java/kr/co/gpgp/auth/dto/OAuthAttributes.java
  src/main/java/kr/co/gpgp/auth/service/CustomOAuth2UserService.java
  src/main/java/kr/co/gpgp/domain/user/entity/User.java
  src/main/java/kr/co/gpgp/web/api/oauth/OAuth2LoginController.java
  src/main/resources/application-oauth.yml
Labels: 🔏 OAuth

#122 feat: 배송 기능 추가
  src/main/java/kr/co/gpgp/domain/delivery/dto/DeliveryResponse.java
  src/main/java/kr/co/gpgp/domain/delivery/entity/Delivery.java
  src/main/java/kr/co/gpgp/domain/delivery/entity/enums/DeliveryStatus.java
  src/main/java/kr/co/gpgp/domain/delivery/exception/DeliveryStatusAuthException.java
  src/main/java/kr/co/gpgp/domain/delivery/repository/DeliveryRepository.java
  src/main/java/kr/co/gpgp/domain/delivery/repository/DeliveryRepositoryCustom.java
  src/main/java/kr/co/gpgp/domain/delivery/repository/DeliveryRepositoryCustomImpl.java
  src/main/java/kr/co/gpgp/domain/delivery/service/DeliveryUserService.java
  src/main/java/kr/co/gpgp/domain/user/entity/Role.java
  src/test/java/kr/co/gpgp/domain/delivery/service/DeliveryServiceTest.java
  src/test/java/kr/co/gpgp/domain/delivery/service/DeliveryUserServiceTest.java
Labels: 🚚 배송

#124 refactor: 배송 권한 관련부분 수정 및 추가
  src/main/java/kr/co/gpgp/domain/address/dto/AddressResponse.java
  src/main/java/kr/co/gpgp/domain/delivery/entity/Delivery.java
  src/main/java/kr/co/gpgp/domain/delivery/entity/enums/DeliveryStatus.java
  src/main/java/kr/co/gpgp/domain/delivery/service/DeliverySellerService.java
  src/main/java/kr/co/gpgp/domain/delivery/service/DeliveryService.java
  src/main/java/kr/co/gpgp/domain/delivery/service/DeliveryUserService.java
  src/main/java/kr/co/gpgp/domain/user/entity/User.java
  src/main/java/kr/co/gpgp/domain/user/service/UserService.java
  src/test/java/kr/co/gpgp/domain/address/entity/AddressTest.java
  src/test/java/kr/co/gpgp/domain/delivery/entity/DeliveryTest.java
  src/test/java/kr/co/gpgp/domain/delivery/service/DeliveryUserServiceTest.java
  src/test/java/kr/co/gpgp/domain/delivery/service/SellerServiceConfigTest.java
  src/test/java/kr/co/gpgp/domain/delivery/service/ServiceConfigTest.java
  src/test/java/kr/co/gpgp/domain/user/entity/UserTest.java
  src/test/java/kr/co/gpgp/domain/user/repository/UserRepositoryTest.java
Labels: 🚚 배송

#206 상품 등록 폼 UI
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/templates/admin/create-new-item-form.html
Labels: 🔲 UI

#210 상품 등록 폼 컨트롤러 구현
  src/main/java/kr/co/gpgp/web/api/item/ItemAdapter.java
  src/main/java/kr/co/gpgp/web/api/item/ItemController.java
  src/main/java/kr/co/gpgp/web/api/item/NewItemCreateForm.java
Labels: 🎁 상품
